### ISSUE TITLE
The "Open customer portal" buton when creating an account fails.

### ISSUE THREAD

**Issue by attackordie** [kyegomez/swarms-platform#3]
When attempting to 'Manage your subscription on Stripe' via the 'Open customer portal' button fails to launch.

This is the [link](https://swarms.world/account) to the account page.

Here is the screenshot of the page and button that is failing.

![Screenshot from 2024-03-10 12-10-18](https://github.com/kyegomez/swarms-platform/assets/20145334/abfcbc75-8c74-43ec-acec-8b18f4f00465)

**Comment by amirrezasalimi** [comment]
fixed
